name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "barleytea362@gmail.com"
          git config --global user.name "barleytea"
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: yarn

      - run: yarn install
      - run: yarn fmt
      - run: yarn deploy